[install]
# Use exact versions for better reproducibility
exact = true

[install.scopes]
# Add any scoped packages if needed

[test]
# Test configuration
preload = ["./src/test-setup.ts"]

[run]
# Runtime configuration
bun = true 